version: "1.0"

services:
  
  # Postgres с примонтированным внешним каталогом для хранения данных. Чтобы при удалении контейнера данные оставались. 
  # Необходимо указывать версию postgres в конфиге
  
  PostgresKeepAlive:
    image: postgres
    container_name: Postgres_KeepAlive
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "client_connection_check_interval=300s"  # САМАЯ ВАЖНАЯ ОПЦИЯ для KeepAlive, доступная с Postgres 14
      - "-c"
      - "tcp_user_timeout=0"
      - "-c"
      - "tcp_keepalives_idle=600"
      - "-c"
      - "tcp_keepalives_interval=60"
      - "-c"
      - "tcp_keepalives_count=5"
    volumes:
      - E:\docker\volumes\postgresKeepAlive:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '7432:5432'